version: '3.3'

# create sql server database
services:
  mmsql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "Auditoria2022!"
        ACCEPT_EULA: "Y"
    volumes:
      - ./volume:/users/db